Lu integracion billeteras suscripciones
teamcubation/byma-front pull request #16
Opened 2024-12-23 12:51 UTC by Lucia-azd

2024-12-23 17:23 UTC, maxizeta commented on heber-especies-front/src/components/billetera/FormBilletera.tsx
> +import { useForm } from "react-hook-form";
ok

2024-12-23 18:29 UTC, maxizeta requested changes

2024-12-23 18:29 UTC, maxizeta commented on heber-especies-front/src/components/suscripcion/SuscripcionList.tsx
>          console.log('data: ', data);
sacar console.log

2024-12-23 18:29 UTC, maxizeta commented on heber-especies-front/src/components/suscripcion/components/utils/createColumn.tsx
> +// });
descomentar o eliminar codigo comentado

2024-12-23 18:29 UTC, maxizeta commented on heber-especies-front/src/components/suscripcion/components/utils/createColumn.tsx
> +  accessorKey: accessorKey as string, // React Table espera un string aquí
eliminar comentario

2024-12-23 18:29 UTC, maxizeta commented on heber-especies-front/src/components/suscripcion/components/utils/createColumn.tsx
> +    const value = row.original[accessorKey]; // Acceso seguro con keyof
eliminar comentario

2024-12-23 18:29 UTC, maxizeta commented on heber-especies-front/src/components/switch/Switch.tsx
> -  size?: 's' | 'l'; // Tamaño opcional: pequeño o grande
sacar comentarios

2024-12-23 18:51 UTC, Lucia-azd commented on heber-especies-front/src/components/suscripcion/components/utils/createColumn.tsx
> +// });
Esto no lo hice yo, por la dudas lo dejo no se si el que lo hizo lo necesite.

2024-12-26 12:20 UTC, maxizeta reviewed
ok

2024-12-26 19:08 UTC, maxizeta submitted a review, later dismissed
ok

2024-12-26 19:09 UTC, maxizeta approved these changes

2024-12-26 19:11 UTC, rogvera approved these changes

2024-12-26 19:13 UTC, julianmarcelolopez approved these changes
Ok

2024-12-26 19:13 UTC, julianmarcelolopez submitted a review, later dismissed

2024-12-26 19:14 UTC, rogvera submitted a review, later dismissed

2024-12-26 19:15 UTC, maxizeta approved these changes

2024-12-26 19:22 UTC, julianmarcelolopez approved these changes

2024-12-26 19:28 UTC, rogvera approved these changes

2024-12-26 19:34 UTC, maxizeta approved these changes

2024-12-26 19:35 UTC, julianmarcelolopez approved these changes

2024-12-26 19:36 UTC, rogvera approved these changes

2024-12-26 19:36 UTC, merged